config/routes.rb
Rails.application.routes.draw do
  
  root to: 'pages#index'

  devise_for :users

  resources :users do
  	resources :articles do
      resources :comments do
        member do
          put 'abuse'
        end
      end
  	end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  
  after_destroy :notify

  validates :title, presence: true
  validates :description, presence: true
  validates :user_id, presence: true

  def count_comments
    self.comments.count
  end

  def author?(user)
    self.user_id == user.id
  end
  
  private 

  def notify
    self.comments.uniq { |c| c.author_id }.each do |comment|
      NotificationMailer.article_removed(c.author,self).deliver
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user

  validates :body, presence: true
  validates :user_id, presence: true
  validates :article_id, presence: true

  def abuse!
  	self.abuse_count+= 1 
  	self.save
  end 

  def overabused?
     self.destroy if self.abuse_count > 3
  end

  def author?(user)
    self.user_id == user.id
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  has_many :comments

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:company_id])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name]) 
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:show, :destroy]
  
  def show 
  end 

  def new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to root_path, notice: 'Article was successfully created.'  
  end

  def destroy 
    if @article.author?(current_user)
      @article.destroy
      redirect_to root_path, notice: 'Article was successfully removed.'
    else
      redirect_to root_path, alert: 'Only article author can remove it!'
    end
  end

  private 

    def article_params
      params.require(:article).permit(:title, :description, :user_id)
    end

    def find_article
      @article = Article.find(params[:id])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_comment, only: [:abuse]

  def create
    @comment = Comment.new(comment_params)
    @comment.save
    redirect_to user_article_path(params[:user_id], 
      params[:article_id]), notice: 'Comment was successfully created.'
  end

  def abuse 
    @comment.abuse!
    @comment.overabused? 
    redirect_to user_article_path(params[:user_id], 
      params[:article_id]), notice: 'Comment was removed because overabused.'
  end

  private 

    def comment_params
      params.require(:comment).permit(:body, :user_id, :article_id)
    end

    def find_comment
      @comment = Comment.find(params[:id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @articles = Article.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def header(text)
  		content_for(:header) { text.to_s }
	end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_article.html.erb
<div class="table-responsive">
  <h2><%= article.title %></h2>
  <%= link_to 'Read', user_article_path(article.user_id, article.id)%>     
</div>
<br>

app/views/articles/_form.html.erb
<%= form_for [ current_user, Article.new ] do |f| %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.submit "Generate topic", class: 'btn btn-primary' %>

<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %> <br>

<%= link_to "Back", :back, class: 'btn btn-default btn-sm' %>

app/views/articles/show.html.erb
<h1><%= @article.title %> (<%= @article.count_comments %>) </h1>
<p><%= @article.description %></p><br>
<% if user_signed_in? %>
  <% if @article.author?(current_user) %>
    <%= link_to 'Remove', user_article_path(current_user.id, @article.id), :method => :delete, class: 'btn btn-danger' %>
  <% end %>
<% end %>
<h3>Comments:</h3>
<% @article.comments.each do |comment| %>
  <p>
    <b><%= comment.user.name %></b><br>
    <%= comment.body %>
    <% if user_signed_in? %>
      <% if !comment.author?(current_user) %>
        <br><%= link_to 'abuse', abuse_user_article_comment_path(@article.user_id, @article.id, comment.id), :method => :put %> 
        <%= comment.abuse_count %> 
      <% end %>
    <% end %>
  </p><br>
<% end %>

<% if user_signed_in? %>
  <%= render 'comments/form' %>
<% end %><br>

<%= link_to "Back", :back, class: 'btn btn-default btn-sm' %><br><br>

app/views/comments/_form.html.erb
<%= form_for [ User.find(@article.user_id), @article, Comment.new ] do |f| %>

  <div class="form-group">
    <%= f.text_area :body, class: 'form-control' %>
  </div>

  <%= f.hidden_field :user_id, value: @article.user_id %>

  <%= f.hidden_field :article_id, value: @article.id %>

   <%= f.submit "Comment", class: 'btn btn-primary' %>

<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Something', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', root_path %></li>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <%= current_user.name %> (<%= current_user.email %>)
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Profile', edit_user_registration_path %></li>
              <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Log In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Basic</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "jquery.rails.js" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render partial: 'layouts/navbar' %>
    
	<div class="container">
	  <% flash.each do |key, value| %>
	    <div class="alert alert-<%= key %>">
	      <%= value %>
	    </div>
	  <% end %>
	</div>

	<%= yield :top_content %>

	<div class="container">
      <h1><%= yield :header %></h1>
		<%= yield %>
	</div>
</body>
</html>

app/views/pages/index.html.erb
<% content_for :top_content do %>
  <div class="jumbotron">
    <div class="container">
      <h2>Welcome, read or post articles for free!</h2>
         <% unless @articles.empty? %>
            <div id="articles">
  			  <%= render @articles %>
		    </div>
         <% end %>
	     <% if !user_signed_in? %>
		      <p>Register to post articles.</p>
		      <p>
		        <%= link_to 'Register', new_user_registration_path, class: 'btn btn-primary btn-lg' %>
		      </p>
	      <% else %>
		      <p>
		        <%= link_to 'New article', new_user_article_path(current_user.id), class: 'btn btn-primary btn-lg' %> 
		      </p>
	      <% end %>
    </div>
  </div>
<% end %>

app/views/pages/index.js.erb
$("#articles").html("<%= escape_javascript(render(@articles)) %>");

app/views/pages/new.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2 padding -top -bottom -small">
    <h1>Welcome</h1>
  </div>
</div>